name: Docs

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate Documentation
      run: cargo doc --verbose --all-features
    - name: Inject Index Meta-Link
      run: echo '<meta http-equiv=refresh content=0;url=image_go_nord/index.html>' > target/doc/index.html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: target/doc
    - name: Cache Generated Files
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/docs
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-docs

