name: CD

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --all-features

  crates_io:
    needs: [ test ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: List Package Contents
      run: cargo package --list
    - name: Publish
      run: cargo publish --verbose
