name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - README.md
    - LICENSE
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: never
  RUST_BACKTRACE: 1

jobs:
  lib:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
        # TODO: test on other windows toolchains?
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Manifest Lock
      run: cargo update
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.3.4
      with:
        rust-version: ${{ matrix.rust }}
    - name: Cache Cargo Registries
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache Build Artifacts
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}-build-artifacts
    - name: Build
      run: cargo +${{matrix.rust}} build --verbose --features serde
    - name: Run tests
      run: cargo +${{ matrix.rust}} test --verbose --features serde
      
  bin:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.3.4
      with:
        rust-version: ${{ matrix.rust }}
    - name: Cache Cargo Registries
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
       https://github.com/rust-lang/rust/issues/84252
    - name: Cache Build Artifacts
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}-build-artifacts
    - name: Build
      run: cargo +${{matrix.rust}} build --verbose --features=clap,color-eyre
    - name: Run tests
      run: cargo +${{ matrix.rust}} test --verbose --features=clap,color-eyre

  docs:

    runs-on: ubuntu-latest
    needs: [native, wasm] # make sure everything works before trying to update the documentation

    steps:
    - uses: actions/checkout@v2
    - name: Get Manifest Lock
      run: cargo update
    - name: Cache Cargo Registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      https://github.com/rust-lang/rust/issues/84252
    - name: Cache Generated Files
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-build-artifacts-docs
    - name: Generate Documentation
      run: cargo doc --verbose --all-features
    - name: Inject Index Meta-Link
      run: echo '<meta http-equiv=refresh content=0;url=image_go_nord/index.html>' > target/doc/index.html
    - name: Deploy to GitHub Pages
      if: ${{ github.event_name != 'pull_request' }}
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: target/doc

  
